### ISSUE TITLE
How to copy callstack

### ISSUE THREAD

**Issue by dimateos** [tianjianchn/code-explorer-vscode#3]
Hello!

Thanks for the extension it looks very cool!

I tied pasting a python and a c++ callstack and I it seems I am unable?
![Image](https://github.com/user-attachments/assets/6baf139d-3d07-4dcb-a10f-657c35418e79)

How is it done?

**Comment by tianjianchn** [comment]
Could you paste your call stack here? callstack is parsed here: 

https://github.com/tianjianchn/code-explorer-vscode/blob/8b34efe43ecbacf189720c03230661cb702b1eb1/src/global-commands.ts#L118

it will match something like
```
<module> (/absolute/path/to/xxx.py:158)
```

**Comment by dimateos** [comment]
This is a c++ project:

    example_glfw_opengl3.exe!main(int __formal, char * * __formal) Line 147 (d:\examples\example_glfw_opengl3\main.cpp:147)
    example_glfw_opengl3.exe!invoke_main() Line 79 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79)
    example_glfw_opengl3.exe!__scrt_common_main_seh() Line 288 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
    example_glfw_opengl3.exe!__scrt_common_main() Line 331 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331)
    example_glfw_opengl3.exe!mainCRTStartup(void * __formal) Line 17 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17)
    kernel32.dll!00007ff92028257d() (Unknown Source:0)
    ntdll.dll!00007ff92192aa48() (Unknown Source:0)

**Comment by tianjianchn** [comment]
@dimateos I have published a new version(0.4.6) to support Windows file path. Have a try and welcome any feedback.

**Comment by dimateos** [comment]
Hello! just tried it and the issue persist, I cannot paste the callstack!

**Comment by tianjianchn** [comment]
> This is a c++ project:
> 
> ```
> example_glfw_opengl3.exe!main(int __formal, char * * __formal) Line 147 (d:\examples\example_glfw_opengl3\main.cpp:147)
> example_glfw_opengl3.exe!invoke_main() Line 79 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79)
> example_glfw_opengl3.exe!__scrt_common_main_seh() Line 288 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
> example_glfw_opengl3.exe!__scrt_common_main() Line 331 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331)
> example_glfw_opengl3.exe!mainCRTStartup(void * __formal) Line 17 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17)
> kernel32.dll!00007ff92028257d() (Unknown Source:0)
> ntdll.dll!00007ff92192aa48() (Unknown Source:0)
> ```

it's working for your example:

<img width="920" alt="Image" src="https://github.com/user-attachments/assets/c784b78e-894b-4e0e-b28e-7acbef0db5bf" />

**Comment by dimateos** [comment]
Well in my end its the same, I restarted vscode etc:

![Image](https://github.com/user-attachments/assets/f146dbf9-0b1d-4fa1-a863-8913d9d912fb)

Probably it has to do with the OS?

```
Version: 1.92.2 (system setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```
